import NavBar from '@/components/navigation/navbar/navBar'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import React from 'react'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

const NavigationLinks = [
  { label: 'Movies', route: '/movies' },
  { label: 'TV Shows', route: '/tvShows' },
  { label: 'About', route: '/about' }
]

export default function RootLayout ({
  children
}: {
  children: React.ReactNode
}) {
  return (
    <html lang='en'>
      <head>
        <title>Rankovies</title>
      </head>
      <body className={inter.className}>
        <header>
          <NavBar navLinks={NavigationLinks} />
        </header>
        {children}
      </body>
    </html>
  )
}
